# Generated by Django 2.2.5 on 2019-11-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=250)),
                ('major', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=250)),
                ('icon_url', models.CharField(default='', max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('logo_url', models.CharField(default='', max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('still_employed', models.BooleanField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(default='', max_length=250)),
                ('subheading', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('link_url', models.CharField(default='', max_length=250)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('category-1', 'Category-1'), ('category-2', 'Category-2'), ('category-3', 'Category-3')], default='category-1', max_length=10)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('photo_url', models.CharField(default='', max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('linkedin_url', models.CharField(default='', max_length=250)),
                ('github_url', models.CharField(default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('color_main', models.CharField(default='007BFF', max_length=6)),
                ('color_accent', models.CharField(default='4682B4', max_length=6)),
                ('color_text', models.CharField(default='000000', max_length=6)),
                ('color_background', models.CharField(default='FFFFFF', max_length=6)),
                ('title_section_1', models.CharField(default='About', max_length=50)),
                ('title_section_2', models.CharField(default='Experience', max_length=50)),
                ('title_section_3', models.CharField(default='Education', max_length=50)),
                ('title_section_4', models.CharField(default='Skills', max_length=50)),
                ('title_section_5', models.CharField(default='Portfolio', max_length=50)),
                ('skill_category_1', models.CharField(default='Languages', max_length=50)),
                ('skill_category_2', models.CharField(default='Frameworks', max_length=50)),
                ('skill_category_3', models.CharField(default='Tools', max_length=50)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
