# Generated by Django 2.2.5 on 2019-11-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_auto_20191121_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-end_date',)},
        ),
    ]
