# Generated by Django 2.2.5 on 2019-10-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='school',
            field=models.CharField(default='', max_length=250),
        ),
    ]
