# Generated by Django 2.2.5 on 2019-10-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_degree_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='degree',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(),
        ),
    ]
