# Generated by Django 2.2.5 on 2019-10-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191010_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_url',
        ),
    ]
