# Generated by Django 2.2.5 on 2019-11-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_skill_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
