# Generated by Django 2.2.5 on 2019-11-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=250)),
                ('subheading', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('link_url', models.CharField(default='', max_length=250)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo_url', models.CharField(default='', max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title_section_1', models.CharField(default='About', max_length=50)),
                ('title_section_2', models.CharField(default='Experience', max_length=50)),
                ('title_section_3', models.CharField(default='Education', max_length=50)),
                ('title_section_4', models.CharField(default='Skills', max_length=50)),
                ('title_section_5', models.CharField(default='Portfolio', max_length=50)),
                ('skill_category_1', models.CharField(default='Languages', max_length=50)),
                ('skill_category_2', models.CharField(default='Frameworks', max_length=50)),
                ('skill_category_3', models.CharField(default='Tools', max_length=50)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('category-1', 'Category-1'), ('category-2', 'Category-2'), ('category-3', 'Category-3')], default='category-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='logo_url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
