# Generated by Django 2.2.5 on 2019-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191119_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='icon_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='degree',
            name='school',
            field=models.CharField(max_length=250),
        ),
    ]
