# Generated by Django 2.2.5 on 2019-11-19 19:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191119_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_accent',
            field=colorfield.fields.ColorField(default='#4682B4', max_length=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='color_background',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='color_main',
            field=colorfield.fields.ColorField(default='#007BFF', max_length=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='color_text',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
