# Generated by Django 2.2.5 on 2019-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191119_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
