# Generated by Django 2.2.5 on 2019-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191119_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='color_accent',
            field=models.CharField(default='4682B4', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color_background',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color_main',
            field=models.CharField(default='007BFF', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color_text',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
